name: Build Windows Exe
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install faster-whisper pyinstaller

    - name: Compile Exe via PyInstaller
      run: |
        pyinstaller --onefile --name="Dad_Slovak_Subtitler" make_subtitles.py

    - name: Save Finished Exe
      uses: actions/upload-artifact@v4
      with:
        name: Windows_Executable
        path: dist/Dad_Slovak_Subtitler.exe
